# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADVERT: ROLE_USER
        ROLE_ADVERT_INDEX_OWN: ROLE_USER
        ROLE_ADVERT_INDEX: ROLE_ADVERT_INDEX_OWN
        ROLE_ADVERT_NEW: ROLE_USER
        ROLE_ADVERT_SHOW: ROLE_USER
        ROLE_ADVERT_EDIT_OWN: ROLE_USER
        ROLE_ADVERT_EDIT: ROLE_ADVERT_EDIT_OWN
        ROLE_ADVERT_DELETE_OWN: ROLE_USER
        ROLE_ADVERT_DELETE: ROLE_ADVERT_DELETE_OWN
        ROLE_ADVERT_ADMIN:
            - ROLE_ADVERT
            - ROLE_ADVERT_INDEX
            - ROLE_ADVERT_NEW
            - ROLE_ADVERT_SHOW
            - ROLE_ADVERT_EDIT
            - ROLE_ADVERT_DELETE
        ROLE_USER_INDEX: ROLE_USER
        ROLE_USER_NEW: ROLE_USER
        ROLE_USER_SHOW: ROLE_USER
        ROLE_USER_EDIT: ROLE_USER
        ROLE_USER_DELETE: ROLE_USER
        ROLE_USER_ADMIN:
            - ROLE_USER_INDEX
            - ROLE_USER_NEW
            - ROLE_USER_SHOW
            - ROLE_USER_EDIT
            - ROLE_USER_DELETE
        ROLE_PROFILE_VIEW: ROLE_USER
        ROLE_CLIENT:
            - ROLE_PROFILE_VIEW
            - ROLE_ADVERT
            - ROLE_ADVERT_INDEX_OWN
            - ROLE_ADVERT_EDIT_OWN
            - ROLE_ADVERT_DELETE_OWN
            - ROLE_ADVERT_NEW
            - ROLE_ADVERT_SHOW
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_CLIENT
            - ROLE_ADVERT_ADMIN
            - ROLE_USER_ADMIN
            - ROLE_PROFILE_VIEW
        ROLE_SUPER_ADMIN: ROLE_ADMIN
