# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - '@security.authorization_checker'
            - '@knp_menu.factory'

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createMainMenu]
        shared: false
        tags:
            - { name: knp_menu.menu, alias: main }

    app.user_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createUserMenu]
        shared: false
        tags:
            - { name: knp_menu.menu, alias: user }

    app.upload_listener:
        class: DocumentBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    app.entity.advert:
        class: AppBundle\Entity\Advert

    app.form.type.advert:
        class: AppBundle\Form\Type\AdvertType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type }

    app.form.advert.new:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - AppBundle\Form\Type\AdvertType
            - null
            - { method: POST }

    app.form.advert.new.handler:
        class: AppBundle\Form\Handler\AdvertFormHandler
        arguments:
            - "@app.form.advert.new"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            - "@security.authorization_checker"
            - "@security.token_storage"

    app.form.advert.edit:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - AppBundle\Form\Type\AdvertType
            - null
            - { method: PUT }

    app.form.advert.edit.handler:
        class: AppBundle\Form\Handler\AdvertFormHandler
        arguments:
            - "@app.form.advert.edit"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            - "@security.authorization_checker"
            - "@security.token_storage"

    app.form.advert.delete:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - AppBundle\Form\Type\AdvertType
            - null
            - { method: DELETE }

    app.entity.advertdocument:
        class: AppBundle\Entity\AdvertDocument

    app.form.type.advertdocument:
        class: AppBundle\Form\Type\AdvertDocumentType
        tags:
            - { name: form.type }

    app.form.advertdocument.delete:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - AppBundle\Form\Type\AdvertDocumentType
            - null
            - { method: DELETE }

    app.form.advertdocument.delete.handler:
        class: AppBundle\Form\Handler\AdvertDocumentFormHandler
        arguments:
            - "@app.form.advertdocument.delete"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            - "@security.authorization_checker"
