# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ['@security.context', '@knp_menu.factory']

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createMainMenu]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    app.user_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createUserMenu]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: user }

    app.upload_listener:
        class: DocumentBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
